// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isdyfsybhliwxzhndprt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZHlmc3liaGxpd3h6aG5kcHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTI2ODYsImV4cCI6MjA3MjQ4ODY4Nn0.7QJB9-t9oS4qW4Bzob0FreZkan2RCPhG_Ff1vSuHgJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});